# версия Docker Compose

version: '3.8'

services:
  ewm-service:
    build: main-server
    container_name: ewm-service
    ports:
      - "8080:8080"

  ewm-db:
    container_name: ewm_db
    image: postgres:14-alpine
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_DB=ewm
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres





  stats-server:
    build: stat-server
    container_name: explore-with-me-stats
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/Stats

  stats-db:
    image: postgres:14-alpine
    container_name: explore-with-me-stats-postgres
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=Stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot




