# версия Docker Compose

version: '3.8'

services:


  ewm-service:
    build:
      context: ewm
      dockerfile: Dockerfile
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update




  ewm-db:
    container_name: ewm_db
    image: postgres:14-alpine
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_DB=ewm
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=iamroot





  stats-server:
    build: stat-server
    container_name: explore-with-me-stats
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/Stats

  stats-db:
    image: postgres:14-alpine
    container_name: explore-with-me-stats-postgres
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=Stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot




